apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
components:
    deployment:
      environments:
        - name: dev
          environment_variables:
            - name: DB_SERVER
              value: "${{ secrets.DB_HOST }}"
            - name: DB_NAME
              value: "${{ secrets.DB_NAME }}"
            - name: DB_PORT
              value: "${{ secrets.DB_PORT }}"
            - name: DB_USER
              value: "${{ secrets.DB_USER }}"
            - name: DB_PASSWORD
              value: "${{ secrets.DB_PASSWORD }}"
        - name: prod
          environment_variables:
            - name: DB_SERVER
              value: "${{ secrets.DB_HOST }}"
            - name: DB_NAME
              value: "${{ secrets.DB_NAME }}"
            - name: DB_PORT
              value: "${{ secrets.DB_PORT }}"
            - name: DB_USER
              value: "${{ secrets.DB_USER }}"
            - name: DB_PASSWORD
              value: "${{ secrets.DB_PASSWORD }}"
