openapi: "3.0.0"
info:
  title: MedicaLink API
  description: API documentation for MedicaLink
  version: 1.0.0
servers:
  - url: https://8e2cd8ab-ce5c-4366-bc71-6ee56cdd875f-dev.e1-us-east-azure.choreoapis.dev/medicalinkapi/medicalink-api/v1.0
paths:
  /api/test/admin:
    get:
      summary: Test endpoint with database
      responses:
        '200':
          description: Successful response
  /api/test/forAll:
    get:
      summary: Test endpoint
      responses:
        '200':
          description: Successful response
  /api/test/all:
    get:
      summary: Another endpoint
      responses:
        '200':
          description: Successful response
